package ai.firmus.interop.fhir

import java.time.Instant
import java.time.ZoneId

/**
 * Payloads copied from the shape `AdmissionEvent.toJson()` produces in the Java ingest service.
 *
 * Hand-written rather than generated by a serializer on this side, on purpose. A round-trip test
 * through this service's own `@Serializable` classes proves only that they are self-consistent;
 * these strings are the actual contract, including the two things about it that matter most:
 * fields are emitted in declaration order, and empty fields are *omitted* rather than sent as
 * null (`Json.optional` returns null and `Json.object` drops the key).
 */
object Fixtures {

    val FACILITY_ZONE: ZoneId = ZoneId.of("America/Mexico_City")

    /** An A01 admit with every optional field populated. */
    const val FULL_ADMIT: String = """
        {"schemaVersion":"1.0.0","eventId":"6f1c0f2e-2c3a-4f6b-9a1d-0d1f2a3b4c5d",
        "messageControlId":"MSG00001","messageType":"ADT^A01","sendingApplication":"EPIC_ADT",
        "sendingFacility":"HGS","recordedAt":"2026-08-25T14:30:00Z",
        "patient":{"medicalRecordNumber":"MRN-88421","otherIdentifiers":["IMSS-2211","SSA-77"],
        "familyName":"Núñez Luna","givenName":"Ixequi","birthDate":"1974-03-14",
        "administrativeSex":"M"},
        "encounter":{"visitNumber":"V-0099","patientClass":"I",
        "admitDateTime":"2026-08-25T14:28:00-06:00","attendingClinician":"Ana Ruiz",
        "pointOfCare":"3N","room":"312","bed":"A","facility":"HGS"}}
    """

    /**
     * The minimum the Java side can emit: schemaVersion, eventId and recordedAt are unconditional,
     * both nested objects are always present, and every optional key is absent — including
     * `otherIdentifiers`, which is dropped entirely when the list is empty rather than sent as `[]`.
     */
    const val MINIMAL_ADMIT: String = """
        {"schemaVersion":"1.0.0","eventId":"11111111-2222-3333-4444-555555555555",
        "recordedAt":"2026-08-25T14:30:00Z",
        "patient":{"medicalRecordNumber":"MRN-1"},
        "encounter":{}}
    """

    /** An A28 "add person information" message: demographics only, no PV1, so no visit. */
    const val PERSON_INFO_ONLY: String = """
        {"schemaVersion":"1.0.0","eventId":"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
        "messageControlId":"MSG00007","messageType":"ADT^A28","sendingApplication":"EPIC_ADT",
        "sendingFacility":"HGS","recordedAt":"2026-08-25T09:00:00Z",
        "patient":{"medicalRecordNumber":"MRN-3001","familyName":"Gonçalves","givenName":"José",
        "birthDate":"1990","administrativeSex":"U"},
        "encounter":{}}
    """

    fun event(
        eventId: String = "evt-1",
        messageType: String = "ADT^A01",
        recordedAt: String = "2026-08-25T14:30:00Z",
        sendingFacility: String = "HGS",
        medicalRecordNumber: String = "MRN-88421",
        otherIdentifiers: List<String> = emptyList(),
        familyName: String = "Núñez",
        givenName: String = "Ixequi",
        birthDate: String = "1974-03-14",
        administrativeSex: String = "M",
        visitNumber: String = "V-0099",
        patientClass: String = "I",
        admitDateTime: String = "2026-08-25T14:28:00-06:00",
        attendingClinician: String = "Ana Ruiz",
        pointOfCare: String = "3N",
        room: String = "312",
        bed: String = "A",
        facility: String = "HGS",
    ) = AdmissionEvent(
        schemaVersion = "1.0.0",
        eventId = eventId,
        messageControlId = "MSG00001",
        messageType = messageType,
        sendingApplication = "EPIC_ADT",
        sendingFacility = sendingFacility,
        recordedAt = recordedAt,
        patient = AdmissionEvent.Patient(
            medicalRecordNumber = medicalRecordNumber,
            otherIdentifiers = otherIdentifiers,
            familyName = familyName,
            givenName = givenName,
            birthDate = birthDate,
            administrativeSex = administrativeSex,
        ),
        encounter = AdmissionEvent.Encounter(
            visitNumber = visitNumber,
            patientClass = patientClass,
            admitDateTime = admitDateTime,
            attendingClinician = attendingClinician,
            pointOfCare = pointOfCare,
            room = room,
            bed = bed,
            facility = facility,
        ),
    )

    fun mapper(zone: ZoneId = FACILITY_ZONE) = FhirMapper(
        identifierSystemBase = "urn:firmus:identifier",
        defaultAssigningAuthority = "UNKNOWN",
        facilityZone = zone,
    )

    fun instant(text: String): Instant = Instant.parse(text)

    /** A logger that discards output; nothing under test asserts on log lines except LoggingTest. */
    fun silentLogger() = Logger("test", LogLevel.ERROR, sink = { })
}
